package com.example.mcpclient.service;

import com.example.mcpclient.client.ChatClient;
import com.example.mcpclient.model.SqlQueryResponse;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

@Slf4j
@Service
@RequiredArgsConstructor
public class SqlGeneratorService {

    private final ToolSelectionService toolSelectionService;
    private final ChatClient chatClient;

    private static final String SQL_GENERATION_PROMPT_TEMPLATE = """
            You are an expert SQL query generator. 
            
            User Request: %s
            
            Context from Database Schema: %s
            
            Based on the user's request and the provided database schema context, generate a SQL query.
            Return ONLY the SQL query without any explanations or markdown formatting.
            """;

    /**
     * Generates SQL query based on user prompt using LLM-selected MCP tools and LLM
     *
     * @param prompt User's natural language request
     * @return SQL query generated by LLM
     */
    public SqlQueryResponse generateSqlQuery(String prompt) {
        log.info("Generating SQL query for prompt: {}", prompt);
        
        // Step 1: Use LLM to select and call appropriate MCP tool
        String context = toolSelectionService.selectAndCallTool(prompt);
        log.debug("Fetched context from LLM-selected tool: {}", context);

        // Step 2: Build full prompt with context
        String fullPrompt = String.format(SQL_GENERATION_PROMPT_TEMPLATE, prompt, context);
        
        // Step 3: Use ChatClient to call LLM for SQL generation
        String sqlQuery = chatClient.call(fullPrompt);
        
        log.info("Generated SQL query: {}", sqlQuery);
        
        return SqlQueryResponse.builder()
                .sqlQuery(sqlQuery.trim())
                .context(context)
                .build();
    }
}
